//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientFormKomik.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataRegister", Namespace="http://schemas.datacontract.org/2004/07/ProjectKomik")]
    [System.SerializableAttribute()]
    public partial class DataRegister : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kategoriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string kategori {
            get {
                return this.kategoriField;
            }
            set {
                if ((object.ReferenceEquals(this.kategoriField, value) != true)) {
                    this.kategoriField = value;
                    this.RaisePropertyChanged("kategori");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Peminjaman", Namespace="http://schemas.datacontract.org/2004/07/ProjectKomik")]
    [System.SerializableAttribute()]
    public partial class Peminjaman : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HargaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDPeminjamanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JudulKomikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TanggalPeminjamanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Harga {
            get {
                return this.HargaField;
            }
            set {
                if ((this.HargaField.Equals(value) != true)) {
                    this.HargaField = value;
                    this.RaisePropertyChanged("Harga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDPeminjaman {
            get {
                return this.IDPeminjamanField;
            }
            set {
                if ((object.ReferenceEquals(this.IDPeminjamanField, value) != true)) {
                    this.IDPeminjamanField = value;
                    this.RaisePropertyChanged("IDPeminjaman");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JudulKomik {
            get {
                return this.JudulKomikField;
            }
            set {
                if ((object.ReferenceEquals(this.JudulKomikField, value) != true)) {
                    this.JudulKomikField = value;
                    this.RaisePropertyChanged("JudulKomik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TanggalPeminjaman {
            get {
                return this.TanggalPeminjamanField;
            }
            set {
                if ((object.ReferenceEquals(this.TanggalPeminjamanField, value) != true)) {
                    this.TanggalPeminjamanField = value;
                    this.RaisePropertyChanged("TanggalPeminjaman");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        string Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        string Register(string username, string password, string kategori);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        System.Threading.Tasks.Task<string> RegisterAsync(string username, string password, string kategori);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRegister", ReplyAction="http://tempuri.org/IService1/UpdateRegisterResponse")]
        string UpdateRegister(string username, string password, string kategori, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRegister", ReplyAction="http://tempuri.org/IService1/UpdateRegisterResponse")]
        System.Threading.Tasks.Task<string> UpdateRegisterAsync(string username, string password, string kategori, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRegister", ReplyAction="http://tempuri.org/IService1/DeleteRegisterResponse")]
        string DeleteRegister(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRegister", ReplyAction="http://tempuri.org/IService1/DeleteRegisterResponse")]
        System.Threading.Tasks.Task<string> DeleteRegisterAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DataRegist", ReplyAction="http://tempuri.org/IService1/DataRegistResponse")]
        ClientFormKomik.ServiceReference1.DataRegister[] DataRegist();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DataRegist", ReplyAction="http://tempuri.org/IService1/DataRegistResponse")]
        System.Threading.Tasks.Task<ClientFormKomik.ServiceReference1.DataRegister[]> DataRegistAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/peminjaman", ReplyAction="http://tempuri.org/IService1/peminjamanResponse")]
        string peminjaman(string IDPeminjaman, string TanggalPeminjaman, int Harga, string IDKomik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/peminjaman", ReplyAction="http://tempuri.org/IService1/peminjamanResponse")]
        System.Threading.Tasks.Task<string> peminjamanAsync(string IDPeminjaman, string TanggalPeminjaman, int Harga, string IDKomik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editPeminjaman", ReplyAction="http://tempuri.org/IService1/editPeminjamanResponse")]
        string editPeminjaman(string IDPeminjaman, string TanggalPeminjaman, int Harga, string IDKomik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editPeminjaman", ReplyAction="http://tempuri.org/IService1/editPeminjamanResponse")]
        System.Threading.Tasks.Task<string> editPeminjamanAsync(string IDPeminjaman, string TanggalPeminjaman, int Harga, string IDKomik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletePeminjaman", ReplyAction="http://tempuri.org/IService1/deletePeminjamanResponse")]
        string deletePeminjaman(string IDPeminjaman);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletePeminjaman", ReplyAction="http://tempuri.org/IService1/deletePeminjamanResponse")]
        System.Threading.Tasks.Task<string> deletePeminjamanAsync(string IDPeminjaman);
        
        // CODEGEN: Generating message contract since the wrapper name (Peminjaman) of message PeminjamanRequest does not match the default value (Peminjaman1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Peminjaman", ReplyAction="http://tempuri.org/IService1/PeminjamanResponse")]
        ClientFormKomik.ServiceReference1.PeminjamanResponse Peminjaman1(ClientFormKomik.ServiceReference1.PeminjamanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Peminjaman", ReplyAction="http://tempuri.org/IService1/PeminjamanResponse")]
        System.Threading.Tasks.Task<ClientFormKomik.ServiceReference1.PeminjamanResponse> Peminjaman1Async(ClientFormKomik.ServiceReference1.PeminjamanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Komik", ReplyAction="http://tempuri.org/IService1/KomikResponse")]
        string Komik(string IDKomik, string JudulKomik, string Pengarang, string Tahun);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Komik", ReplyAction="http://tempuri.org/IService1/KomikResponse")]
        System.Threading.Tasks.Task<string> KomikAsync(string IDKomik, string JudulKomik, string Pengarang, string Tahun);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editKomik", ReplyAction="http://tempuri.org/IService1/editKomikResponse")]
        string editKomik(string IDKomik, string JudulKomik, string Pengarang, string Tahun);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editKomik", ReplyAction="http://tempuri.org/IService1/editKomikResponse")]
        System.Threading.Tasks.Task<string> editKomikAsync(string IDKomik, string JudulKomik, string Pengarang, string Tahun);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/hapusKomik", ReplyAction="http://tempuri.org/IService1/hapusKomikResponse")]
        string hapusKomik(string IDKomik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/hapusKomik", ReplyAction="http://tempuri.org/IService1/hapusKomikResponse")]
        System.Threading.Tasks.Task<string> hapusKomikAsync(string IDKomik);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Peminjaman", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PeminjamanRequest {
        
        public PeminjamanRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PeminjamanResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PeminjamanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ClientFormKomik.ServiceReference1.Peminjaman[] PeminjamanResult;
        
        public PeminjamanResponse() {
        }
        
        public PeminjamanResponse(ClientFormKomik.ServiceReference1.Peminjaman[] PeminjamanResult) {
            this.PeminjamanResult = PeminjamanResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClientFormKomik.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClientFormKomik.ServiceReference1.IService1>, ClientFormKomik.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public string Register(string username, string password, string kategori) {
            return base.Channel.Register(username, password, kategori);
        }
        
        public System.Threading.Tasks.Task<string> RegisterAsync(string username, string password, string kategori) {
            return base.Channel.RegisterAsync(username, password, kategori);
        }
        
        public string UpdateRegister(string username, string password, string kategori, int id) {
            return base.Channel.UpdateRegister(username, password, kategori, id);
        }
        
        public System.Threading.Tasks.Task<string> UpdateRegisterAsync(string username, string password, string kategori, int id) {
            return base.Channel.UpdateRegisterAsync(username, password, kategori, id);
        }
        
        public string DeleteRegister(string username) {
            return base.Channel.DeleteRegister(username);
        }
        
        public System.Threading.Tasks.Task<string> DeleteRegisterAsync(string username) {
            return base.Channel.DeleteRegisterAsync(username);
        }
        
        public ClientFormKomik.ServiceReference1.DataRegister[] DataRegist() {
            return base.Channel.DataRegist();
        }
        
        public System.Threading.Tasks.Task<ClientFormKomik.ServiceReference1.DataRegister[]> DataRegistAsync() {
            return base.Channel.DataRegistAsync();
        }
        
        public string peminjaman(string IDPeminjaman, string TanggalPeminjaman, int Harga, string IDKomik) {
            return base.Channel.peminjaman(IDPeminjaman, TanggalPeminjaman, Harga, IDKomik);
        }
        
        public System.Threading.Tasks.Task<string> peminjamanAsync(string IDPeminjaman, string TanggalPeminjaman, int Harga, string IDKomik) {
            return base.Channel.peminjamanAsync(IDPeminjaman, TanggalPeminjaman, Harga, IDKomik);
        }
        
        public string editPeminjaman(string IDPeminjaman, string TanggalPeminjaman, int Harga, string IDKomik) {
            return base.Channel.editPeminjaman(IDPeminjaman, TanggalPeminjaman, Harga, IDKomik);
        }
        
        public System.Threading.Tasks.Task<string> editPeminjamanAsync(string IDPeminjaman, string TanggalPeminjaman, int Harga, string IDKomik) {
            return base.Channel.editPeminjamanAsync(IDPeminjaman, TanggalPeminjaman, Harga, IDKomik);
        }
        
        public string deletePeminjaman(string IDPeminjaman) {
            return base.Channel.deletePeminjaman(IDPeminjaman);
        }
        
        public System.Threading.Tasks.Task<string> deletePeminjamanAsync(string IDPeminjaman) {
            return base.Channel.deletePeminjamanAsync(IDPeminjaman);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientFormKomik.ServiceReference1.PeminjamanResponse ClientFormKomik.ServiceReference1.IService1.Peminjaman1(ClientFormKomik.ServiceReference1.PeminjamanRequest request) {
            return base.Channel.Peminjaman1(request);
        }
        
        public ClientFormKomik.ServiceReference1.Peminjaman[] Peminjaman1() {
            ClientFormKomik.ServiceReference1.PeminjamanRequest inValue = new ClientFormKomik.ServiceReference1.PeminjamanRequest();
            ClientFormKomik.ServiceReference1.PeminjamanResponse retVal = ((ClientFormKomik.ServiceReference1.IService1)(this)).Peminjaman1(inValue);
            return retVal.PeminjamanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientFormKomik.ServiceReference1.PeminjamanResponse> ClientFormKomik.ServiceReference1.IService1.Peminjaman1Async(ClientFormKomik.ServiceReference1.PeminjamanRequest request) {
            return base.Channel.Peminjaman1Async(request);
        }
        
        public System.Threading.Tasks.Task<ClientFormKomik.ServiceReference1.PeminjamanResponse> Peminjaman1Async() {
            ClientFormKomik.ServiceReference1.PeminjamanRequest inValue = new ClientFormKomik.ServiceReference1.PeminjamanRequest();
            return ((ClientFormKomik.ServiceReference1.IService1)(this)).Peminjaman1Async(inValue);
        }
        
        public string Komik(string IDKomik, string JudulKomik, string Pengarang, string Tahun) {
            return base.Channel.Komik(IDKomik, JudulKomik, Pengarang, Tahun);
        }
        
        public System.Threading.Tasks.Task<string> KomikAsync(string IDKomik, string JudulKomik, string Pengarang, string Tahun) {
            return base.Channel.KomikAsync(IDKomik, JudulKomik, Pengarang, Tahun);
        }
        
        public string editKomik(string IDKomik, string JudulKomik, string Pengarang, string Tahun) {
            return base.Channel.editKomik(IDKomik, JudulKomik, Pengarang, Tahun);
        }
        
        public System.Threading.Tasks.Task<string> editKomikAsync(string IDKomik, string JudulKomik, string Pengarang, string Tahun) {
            return base.Channel.editKomikAsync(IDKomik, JudulKomik, Pengarang, Tahun);
        }
        
        public string hapusKomik(string IDKomik) {
            return base.Channel.hapusKomik(IDKomik);
        }
        
        public System.Threading.Tasks.Task<string> hapusKomikAsync(string IDKomik) {
            return base.Channel.hapusKomikAsync(IDKomik);
        }
    }
}
